[package]
name = "smartgarden-hardware-control"
version = "0.1.0"
authors = ["Luca.Mueller"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.7"
failure = "0.1.5"
failure_derive = "0.1.5"